export const state = [
     { name: "Andhra Pradesh", code: "AP" },
     { name: "Arunachal Pradesh", code: "AR" },
     { name: "Assam", code: "AS" },
     { name: "Bihar", code: "BR" },
     { name: "Chhattisgarh", code: "CT" },
     { name: "Goa", code: "GA" },
     { name: "Gujarat", code: "GJ" },
     { name: "Haryana", code: "HR" },
     { name: "Himachal Pradesh", code: "HP" },
     { name: "Jharkhand", code: "JH" },
     { name: "Karnataka", code: "KA" },
     { name: "Kerala", code: "KL" },
     { name: "Madhya Pradesh", code: "MP" },
     { name: "Maharashtra", code: "MH" },
     { name: "Manipur", code: "MN" },
     { name: "Meghalaya", code: "ML" },
     { name: "Mizoram", code: "MZ" },
     { name: "Nagaland", code: "NL" },
     { name: "Odisha", code: "OR" },
     { name: "Punjab", code: "PB" },
     { name: "Rajasthan", code: "RJ" },
     { name: "Sikkim", code: "SK" },
     { name: "Tamil Nadu", code: "TN" },
     { name: "Telangana", code: "TG" },
     { name: "Tripura", code: "TR" },
     { name: "Uttar Pradesh", code: "UP" },
     { name: "Uttarakhand", code: "UT" },
     { name: "West Bengal", code: "WB" },
     { name: "Andaman and Nicobar Islands", code: "AN" },
     { name: "Chandigarh", code: "CH" },
     { name: "Dadra and Nagar Haveli and Daman and Diu", code: "DN" },
     { name: "Lakshadweep", code: "LD" },
     { name: "Delhi", code: "DL" },
     { name: "Puducherry", code: "PY" },
     { name: "Ladakh", code: "LA" },
     { name: "Jammu and Kashmir", code: "JK" },
];


export const district = [
     { name: "Ajmer" },
     { name: "Alwar" },
     { name: "Banswara" },
     { name: "Baran" },
     { name: "Barmer" },
     { name: "Bharatpur" },
     { name: "Bhilwara" },
     { name: "Bikaner" },
     { name: "Bundi" },
     { name: "Chittorgarh" },
     { name: "Churu" },
     { name: "Dausa" },
     { name: "Dholpur" },
     { name: "Dungarpur" },
     { name: "Hanumangarh" },
     { name: "Jaipur" },
     { name: "Jaisalmer" },
     { name: "Jalore" },
     { name: "Jhalawar" },
     { name: "Jhunjhunu" },
     { name: "Jodhpur" },
     { name: "Karauli" },
     { name: "Kota" },
     { name: "Nagaur" },
     { name: "Pali" },
     { name: "Pratapgarh" },
     { name: "Rajsamand" },
     { name: "Sawai Madhopur" },
     { name: "Sikar" },
     { name: "Sirohi" },
     { name: "Sri Ganganagar" },
     { name: "Tonk" },
     { name: "Udaipur" },
];

export const tehsil = [
     { name: "Amber" },
     { name: "Bassi" },
     { name: "Chaksu" },
     { name: "Jamwa Ramgarh" },
     { name: "Jhotwara" },
     { name: "Kotputli" },
     { name: "Maujmabad" },
     { name: "Phagi" },
     { name: "Phulera" },
     { name: "Sanganer" },
     { name: "Shahpura" },
     { name: "Viratnagar" },
];

export const ps = [
     { name: "Vaishali Nagar" },
     { name: "Vidhyadhar Nagar" },
     { name: "Mansarovar" },
     { name: "Shyam Nagar" },
     { name: "Chitrakoot" },
     { name: "Sodala" },
     { name: "Bani Park" },
     { name: "Jawahar Circle" },
     { name: "Malviya Nagar" },
     { name: "Sanganer" },
];

export const formInput = [
     {
          name: "state",
          title: "State",
          type: "dropdown",
          requird: true,
          placeholder: "---slect---",
     },
     {
          name: "district",
          title: "District",
          type: "dropdown",
          requird: true,
          placeholder: "---slect---",
     },
     {
          name: "tehsil",
          title: "Tehsil",
          type: "dropdown",
          requird: true,
          placeholder: "---slect---",
     },
     {
          name: "ps",
          title: "Police Station",
          type: "dropdown",
          requird: true,
          placeholder: "---slect---",
     },
     {
          name: "city",
          title: "City",
          type: "check",
          requird: true,
          checkValue: [
               { value: "rajasthan", key: "rj" },
               { value: "delhi", key: "dl" },
               { value: "uk", key: "uk" },
          ],
     },
];

export const preValue = {
     state: "",
     district: "",
     tehsil: "",
     ps: "",
     city:'',
};