export const अदालतकेप्रकार = [
     { name: "उच्च न्यायालय (High Court)" },
     { name: "जिला न्यायालय (District Court)" },
     { name: "मजिस्ट्रेट न्यायालय (Magistrate Court)" },
     { name: "परिवार न्यायालय (Family Court)" },
     { name: "उपभोक्ता फोरम (Consumer Forum)" },
     { name: "औद्योगिक न्यायालय (Industrial Court)" },
     { name: "सत्र न्यायालय (Sessions Court)" },
     { name: "सिविल न्यायालय (Civil Court)" },
     { name: "फास्ट ट्रैक कोर्ट (Fast Track Court)" },
     { name: "वाणिज्यिक न्यायालय (Commercial Court)" },
     { name: "मोटर वाहन न्यायालय (Motor Accident Claims Tribunal)" },
     { name: "निगम न्यायालय (Corporation Court)" },
     { name: "राजस्व न्यायालय (Revenue Court)" },
     { name: "लोक अदालत (Lok Adalat)" },
];

export const कीगईकार्यवाही = [
     { name: "प्राथमिकी दर्ज (FIR Registered)" },
     { name: "न्यायिक सुनवाई (Judicial Hearing)" },
     { name: "जमानत याचिका (Bail Application)" },
     { name: "चार्जशीट दाखिल (Chargesheet Filed)" },
     { name: "आरोपी की पेशी (Accused's Appearance)" },
     { name: "दलीलों का प्रस्तुतिकरण (Presentation of Arguments)" },
     { name: "साक्ष्य प्रस्तुतिकरण (Presentation of Evidence)" },
     { name: "फैसला सुनाया गया (Verdict Pronounced)" },
     { name: "अपील दायर (Appeal Filed)" },
     { name: "अंतिम निर्णय (Final Judgment)" },
     { name: "समझौता (Settlement)" },
     { name: "दंडादेश (Sentence Pronounced)" },
];

export const राज् = [
     { name: "आंध्र प्रदेश" },
     { name: "अरुणाचल प्रदेश" },
     { name: "असम" },
     { name: "बिहार" },
     { name: "छत्तीसगढ़" },
     { name: "गोवा" },
     { name: "गुजरात" },
     { name: "हरियाणा" },
     { name: "हिमाचल प्रदेश" },
     { name: "झारखंड" },
     { name: "कर्नाटक" },
     { name: "केरल" },
     { name: "मध्य प्रदेश" },
     { name: "महाराष्ट्र" },
     { name: "मणिपुर" },
     { name: "मेघालय" },
     { name: "मिजोरम" },
     { name: "नागालैंड" },
     { name: "ओडिशा" },
     { name: "पंजाब" },
     { name: "राजस्थान" },
     { name: "सिक्किम" },
     { name: "तमिलनाडु" },
     { name: "तेलंगाना" },
     { name: "त्रिपुरा" },
     { name: "उत्तर प्रदेश" },
     { name: "उत्तराखंड" },
     { name: "पश्चिम बंगाल" },
     { name: "अंडमान और निकोबार द्वीपसमूह" },
     { name: "चंडीगढ़" },
     { name: "दादरा और नगर हवेली और दमन और दीव" },
     { name: "लक्षद्वीप" },
     { name: "दिल्ली" },
     { name: "पुडुचेरी" },
     { name: "लद्दाख" },
     { name: "जम्मू और कश्मीर" },
];

export const जिला = [
     { name: "अजमेर" },
     { name: "अलवर" },
     { name: "बांसवाड़ा" },
     { name: "बारां" },
     { name: "बाड़मेर" },
     { name: "भरतपुर" },
     { name: "भीलवाड़ा" },
     { name: "बीकानेर" },
     { name: "बूंदी" },
     { name: "चित्तौड़गढ़" },
     { name: "चूरू" },
     { name: "डूंगरपुर" },
     { name: "हनुमानगढ़" },
     { name: "जयपुर" },
     { name: "जैसलमेर" },
     { name: "जालोर" },
     { name: "झालावाड़" },
     { name: "झुंझुनू" },
     { name: "जोधपुर" },
     { name: "करौली" },
     { name: "कोटा" },
     { name: "नागौर" },
     { name: "पाली" },
     { name: "प्रतापगढ़" },
     { name: "राजसमंद" },
     { name: "सवाई माधोपुर" },
     { name: "सीकर" },
     { name: "सिरोही" },
     { name: "श्री गंगानगर" },
     { name: "टोंक" },
     { name: "उदयपुर" },
];

export const पुलिसस्टेशन = [
     { name: "वैशाली नगर" },
     { name: "विद्याधर नगर" },
     { name: "मानसरोवर" },
     { name: "श्याम नगर" },
     { name: "चित्रकूट" },
     { name: "सोडाला" },
     { name: "बानी पार्क" },
     { name: "जवाहर सर्कल" },
     { name: "मालवीय नगर" },
     { name: "सांगानेर" },
     { name: "शास्त्री नगर" },
     { name: "अल्बर्ट हॉल" },
     { name: "झोटवाड़ा" },
     { name: "कालवाड़" },
     { name: "नाहरगढ़" },
     { name: "मुरलीपुरा" },
     { name: "गणेशपुरा" },
     { name: "प्रताप नगर" },
     { name: "शिप्रा पथ" },
     { name: "बगरू" },
     { name: "मध्यमिक शिक्षा मंडल" },
     { name: "हसनपुरा" },
     { name: "भांकरोटा" },
     { name: "अम्बाबाड़ी" },
     { name: "गोविंदगढ़" },
     { name: "कोटखावदा" },
     { name: "सदाशिव नगर" },
     { name: "बेलानी मंडल" },
];

export const बीटसं = [
     { name: "बीट नं 1" },
     { name: "बीट नं 2" },
     { name: "बीट नं 3" },
     { name: "बीट नं 4" },
     { name: "बीट नं 5" },
     { name: "बीट नं 6" },
     { name: "बीट नं 7" },
     { name: "बीट नं 8" },
     { name: "बीट नं 9" },
     { name: "बीट नं 10" },
];

export const कार्यपालकन्‍यायाधीशकानाम = [
     { name: "कार्यपालक न्यायाधीश 1" },
     { name: "कार्यपालक न्यायाधीश 2" },
     { name: "कार्यपालक न्यायाधीश 3" },
     { name: "कार्यपालक न्यायाधीश 4" },
     { name: "कार्यपालक न्यायाधीश 5" },
];

export const inputFild1 = [
     {
          name: "गिरफ्तारीकीस्थिति",
          type: "radio",
          title: "गिरफ्तारी की स्थिति",
          required: true,
          option: [
               { value: " गिरफ्तार", lable: " गिरफ्तार" },
               { value: "समर्पण", lable: "समर्पण" },
          ],
     },
     {
          name: "प्राथमिकीप्रकरणसंख्‍या",
          type: "text",
          title: "प्राथमिकी / लघु प्रकरण संख्‍या",
          required: true,
          placeholder: "प्राथमिकी",
     },
     {
          name: "गिरफ्तारीकीतिथि",
          type: "date",
          title: "गिरफ्तारी की तिथि / समय",
          placeholder: "गिरफ्तारी की तिथि",
          required: true,
     },
     {
          name: "जनरलडायरीप्रवेशसं",
          type: "text",
          title: "जनरल डायरी प्रवेश सं",
          placeholder: "जनरल डायरी प्रवेश सं",
          required: true,
     },
     {
          name: "अभियुक्तकाअक्षरांकीयकोड",
          type: "text",
          title: "अभियुक्त का अक्षरांकीय कोड",
          required: false,

          placeholder: "अभियुक्त का अक्षरांकीय कोड",
     },
     {
          name: "न्यायालयकेनाम",
          type: "text",
          title: "न्यायालय के नाम",
          placeholder: "न्यायालय के नाम",
          required: false,
     },
     {
          name: "अदालतकेप्रकार",
          type: "dropdown",
          title: "अदालत के प्रकार",
          placeholder: "---चयन---",
          required: false,
     },
     {
          name: "कीगईकार्यवाही",
          type: "dropdown",
          title: "की गई कार्यवाही",
          required: false,

          placeholder: "---चयन---",
     },
];

export const inputFild2 = [
     {
          name: "राज्",
          type: "dropdown",
          title: "राज्य (गिरफ्तारी का स्थान)",
          required: true,

          placeholder: "---चयन---",
     },
     {
          name: "जिला",
          type: "dropdown",
          title: "जिला (गिरफ्तारी का स्थान)",
          required: true,

          placeholder: "---चयन---",
     },
     {
          name: "पुलिसस्टेशन",
          type: "dropdown",
          title: "पुलिस स्टेशन (गिरफ्तारी की जगह )",
          required: true,

          placeholder: "---चयन---",
     },
     {
          name: "बीटसं",
          type: "dropdown",
          title: "बीट सं.",
          required: false,

          placeholder: "---चयन---",
     },
     {
          name: "कार्यपालकन्‍यायाधीशकानाम",
          type: "dropdown",
          title: "कार्यपालक न्‍यायाधीश का नाम",
          required: true,

          placeholder: "---चयन---",
     },
     {
          name: "पुलिसस्टेशनमेंसूचनाकीतिथि",
          type: "date",
          title: "पुलिस स्टेशन में सूचना की तिथि",
          required: true,

          placeholder: "पुलिस स्टेशन में सूचना की तिथि",
     },
     {
          name: "गिरफ्तारीकेजगह",
          type: "textarea",
          title: "गिरफ्तारी के जगह",
          required: true,

          placeholder: "गिरफ्तारी के जगह",
     },
];

export const preValue = {
     गिरफ्तारीकीस्थिति: "",
     प्राथमिकीप्रकरणसंख्‍या: "",
     गिरफ्तारीकीतिथि: "",
     जनरलडायरीप्रवेशसं: "",
     अभियुक्तकाअक्षरांकीयकोड: "",
     न्यायालयकेनाम: "",
     अदालतकेप्रकार: "",
     कीगईकार्यवाही: "",
     राज्: "",
     जिला: "",
     पुलिसस्टेशन: "",
     बीटसं: "",
     कार्यपालकन्‍यायाधीशकानाम: "",
     पुलिसस्टेशनमेंसूचनाकीतिथि: "",
     गिरफ्तारीकेजगह: "",
};