export const inputFild1 = [
     {
          name: "सूचनाकीतारीखऔरसमय",
          type: "date",
          title: "सूचना की तारीख और समय",
          required: true,
          placeholder: "सूचना की तारीख और समय",
     },
     {
          name: "सूचितसंबंधीकानाम",
          type: "text",
          title: "सूचित संबंधी का नाम",
          required: true,
          placeholder: "संबंधी का नाम",
     },
     {
          name: "गिरफ्तारव्यक्तिकेसाथसंबंध",
          type: "dropdown",
          title: "गिरफ्तार व्यक्ति के साथ संबंध",
          required: true,
          placeholder: "-----चयन-----",
     },

     {
          name: "सूचनाकीविधि",
          type: "dropdown",
          title: "सूचना की विधि",
          required: true,
          placeholder: "-----चयन-----",
     },
];

export const inputFild2 = [
     {
          name: "मकानसं",
          type: "text",
          title: "मकान सं",
          required: false,
          placeholder: "English Characters Only",
     },
     {
          name: "सड़ककानाम",
          type: "text",
          title: "सड़क का नाम",
          required: false,
          placeholder: "English Characters Only",
     },
     {
          name: "कॉलोनीइलाक़ाक्षेत्र",
          type: "text",
          title: "कॉलोनी / इलाक़ा /क्षेत्र",
          required: false,
          placeholder: "English Characters Only",
     },
     {
          name: "ग्रामनगरशहर",
          type: "text",
          title: "ग्राम / नगर / शहर",
          required: false,
          placeholder: "English Characters Only",
     },
     {
          name: "तहसीलब्लॉकमंडल",
          type: "text",
          title: "तहसील / ब्लॉक / मंडल",
          required: false,
          placeholder: "English Characters Only",
     },
     {
          name: "वर्तमानपता",
          type: "radio",
          title: "तहसील / ब्लॉक / मंडल",
          required: false,
          radio: [
               { name: "हाँ", lable: "हाँ" },
               { name: "नहीं", lable: "नहीं" },
          ],
     },
];

export const inputFild3 = [
     {
          name: "देश",
          type: "dropdown",
          title: "देश",
          required: false,
          placeholder: "-----चयन-----",
     },
     {
          name: "राज्य",
          type: "dropdown",
          title: "राज्य",
          required: false,
          placeholder: "-----चयन-----",
     },
     {
          name: "जिला",
          type: "dropdown",
          title: "जिला",
          required: false,
          placeholder: "-----चयन-----",
     },
     {
          name: "पुलिसस्टेशन",
          type: "dropdown",
          title: "पुलिस स्टेशन",
          required: false,
          placeholder: "-----चयन-----",
     },
     {
          name: "पिनकोड",
          type: "text",
          title: "पिन कोड",
          required: false,
          placeholder: "पिन कोड",
     },
];
export const preValue = {
     सूचनाकीतारीखऔरसमय: "",
     सूचितसंबंधीकानाम: "",
     गिरफ्तारव्यक्तिकेसाथसंबंध: "",
     सूचनाकीविधि: "",
     मकानसं: "",
     सड़ककानाम: "",
     कॉलोनीइलाक़ाक्षेत्र: "",
     ग्रामनगरशहर: "",
     तहसीलब्लॉकमंडल: "",
     वर्तमानपता: "",
     देश: "",
     राज्य: "",
     जिला: "",
     पुलिसस्टेशन: "",
     पिनकोड: "",
};

export const गिरफ्तारव्यक्तिकेसाथसंबंध = [
     { name: "अन्य" },
     { name: "अभिभावक" },
     { name: "चचेरा ममेरा मौसेरा या फुफेरा भाई" },
     { name: "चाचा" },
     { name: "चाची" },
     { name: "छात्र/शिष्य" },
     { name: "दादा" },
     { name: "दादी" },
     { name: "दामाद" },
     { name: "दूर के रिश्तेदार" },
     { name: "दोस्त" },
     { name: "नाना" },
     { name: "नानी" },
     { name: "पड़ोसी" },
     { name: "पति" },
     { name: "पत्नी" },
     { name: "परदादा" },
     { name: "परदादी" },
     { name: "पिता" },
     { name: "पुरुष-मित्र" },
     { name: "पूर्व पत्नी" },
     { name: "पूर्व-पति" },
     { name: "पोता" },
     { name: "पोती" },
     { name: "पौषक पिता" },
     { name: "पौष्य पुत्र" },
     { name: "बहन" },
     { name: "बहनोई" },
     { name: "बहू" },
     { name: "बेटा" },
     { name: "बेटी" },
     { name: "भतीजा/भांजा" },
     { name: "भतीजी/ भांजी" },
     { name: "भाई" },
     { name: "भावज" },
     { name: "भू - स्वामी" },
     { name: "भूस्वामिनी" },
];

export const सूचनाकीविधि = [
     { name: "अन्य साधन" },
     { name: "ईमेल द्वारा" },
     { name: "एसएमएस/एमएमएस द्वारा" },
     { name: "डाक द्वारा" },
     { name: "फैक्स द्वारा" },
     { name: "फोन द्वारा" },
     { name: "वायरलेस" },
     { name: "व्यक्ति द्वारा" },
];

export const देश = [
     { name: "Afghanistan" },
     { name: "Albania" },
     { name: "Algeria" },
     { name: "Andorra" },
     { name: "Angola" },
     { name: "Antigua and Barbuda" },
     { name: "Argentina" },
     { name: "Armenia" },
     { name: "Australia" },
     { name: "Austria" },
     { name: "Azerbaijan" },
     { name: "Bahamas" },
     { name: "Bahrain" },
     { name: "Bangladesh" },
     { name: "Barbados" },
     { name: "Belarus" },
     { name: "Belgium" },
     { name: "Belize" },
     { name: "Benin" },
     { name: "Bhutan" },
     { name: "Bolivia" },
     { name: "Bosnia and Herzegovina" },
     { name: "Botswana" },
     { name: "Brazil" },
     { name: "Brunei" },
     { name: "Bulgaria" },
     { name: "Burkina Faso" },
     { name: "Burundi" },
     { name: "Cabo Verde" },
     { name: "Cambodia" },
     { name: "Cameroon" },
     { name: "Canada" },
     { name: "Central African Republic" },
     { name: "Chad" },
     { name: "Chile" },
     { name: "China" },
     { name: "Colombia" },
     { name: "Comoros" },
     { name: "Congo (Congo-Brazzaville)" },
     { name: "Costa Rica" },
     { name: "Croatia" },
     { name: "Cuba" },
     { name: "Cyprus" },
     { name: "Czechia (Czech Republic)" },
     { name: "Democratic Republic of the Congo" },
     { name: "Denmark" },
     { name: "Djibouti" },
     { name: "Dominica" },
     { name: "Dominican Republic" },
     { name: "Ecuador" },
     { name: "Egypt" },
     { name: "El Salvador" },
     { name: "Equatorial Guinea" },
     { name: "Eritrea" },
     { name: "Estonia" },
     { name: "Eswatini" },
     { name: "Ethiopia" },
     { name: "Fiji" },
     { name: "Finland" },
     { name: "France" },
     { name: "Gabon" },
     { name: "Gambia" },
     { name: "Georgia" },
     { name: "Germany" },
     { name: "Ghana" },
     { name: "Greece" },
     { name: "Grenada" },
     { name: "Guatemala" },
     { name: "Guinea" },
     { name: "Guinea-Bissau" },
     { name: "Guyana" },
     { name: "Haiti" },
     { name: "Honduras" },
     { name: "Hungary" },
     { name: "Iceland" },
     { name: "India" },
     { name: "Indonesia" },
     { name: "Iran" },
     { name: "Iraq" },
     { name: "Ireland" },
     { name: "Israel" },
     { name: "Italy" },
     { name: "Jamaica" },
     { name: "Japan" },
     { name: "Jordan" },
     { name: "Kazakhstan" },
     { name: "Kenya" },
     { name: "Kiribati" },
     { name: "Kuwait" },
     { name: "Kyrgyzstan" },
     { name: "Laos" },
     { name: "Latvia" },
     { name: "Lebanon" },
     { name: "Lesotho" },
     { name: "Liberia" },
     { name: "Libya" },
     { name: "Liechtenstein" },
     { name: "Lithuania" },
     { name: "Luxembourg" },
     { name: "Madagascar" },
     { name: "Malawi" },
     { name: "Malaysia" },
     { name: "Maldives" },
     { name: "Mali" },
     { name: "Malta" },
     { name: "Marshall Islands" },
     { name: "Mauritania" },
     { name: "Mauritius" },
     { name: "Mexico" },
     { name: "Micronesia" },
     { name: "Moldova" },
     { name: "Monaco" },
     { name: "Mongolia" },
     { name: "Montenegro" },
     { name: "Morocco" },
     { name: "Mozambique" },
     { name: "Myanmar (Burma)" },
     { name: "Namibia" },
     { name: "Nauru" },
     { name: "Nepal" },
     { name: "Netherlands" },
     { name: "New Zealand" },
     { name: "Nicaragua" },
     { name: "Niger" },
     { name: "Nigeria" },
     { name: "North Korea" },
     { name: "North Macedonia" },
     { name: "Norway" },
     { name: "Oman" },
     { name: "Pakistan" },
     { name: "Palau" },
     { name: "Palestine" },
     { name: "Panama" },
     { name: "Papua New Guinea" },
     { name: "Paraguay" },
     { name: "Peru" },
     { name: "Philippines" },
     { name: "Poland" },
];

export const राज्य = [
     { name: "Andhra Pradesh" },
     { name: "Arunachal Pradesh" },
     { name: "Assam" },
     { name: "Bihar" },
     { name: "Chhattisgarh" },
     { name: "Goa" },
     { name: "Gujarat" },
     { name: "Haryana" },
     { name: "Himachal Pradesh" },
     { name: "Jharkhand" },
     { name: "Karnataka" },
     { name: "Kerala" },
     { name: "Madhya Pradesh" },
     { name: "Maharashtra" },
     { name: "Manipur" },
     { name: "Meghalaya" },
     { name: "Mizoram" },
     { name: "Nagaland" },
     { name: "Odisha" },
     { name: "Punjab" },
     { name: "Rajasthan" },
     { name: "Sikkim" },
     { name: "Tamil Nadu" },
     { name: "Telangana" },
     { name: "Tripura" },
     { name: "Uttar Pradesh" },
     { name: "Uttarakhand" },
     { name: "West Bengal" },
     { name: "Andaman and Nicobar Islands" },
     { name: "Chandigarh" },
     { name: "Dadra and Nagar Haveli and Daman and Diu" },
     { name: "Lakshadweep" },
     { name: "Delhi" },
     { name: "Puducherry" },
];

export const जिला = [
     { name: "Ajmer" },
     { name: "Alwar" },
     { name: "Banswara" },
     { name: "Baran" },
     { name: "Barmer" },
     { name: "Bharatpur" },
     { name: "Bhilwara" },
     { name: "Bikaner" },
     { name: "Bundi" },
     { name: "Chittorgarh" },
     { name: "Churu" },
     { name: "Dausa" },
     { name: "Dholpur" },
     { name: "Dungarpur" },
     { name: "Hanumangarh" },
     { name: "Jaipur" },
     { name: "Jaisalmer" },
     { name: "Jalore" },
     { name: "Jhalawar" },
     { name: "Jhunjhunu" },
     { name: "Jodhpur" },
     { name: "Karauli" },
     { name: "Kota" },
     { name: "Nagaur" },
     { name: "Pali" },
     { name: "Pratapgarh" },
     { name: "Rajsamand" },
     { name: "Sawai Madhopur" },
     { name: "Sikar" },
     { name: "Sirohi" },
     { name: "Sri Ganganagar" },
     { name: "Tonk" },
     { name: "Udaipur" },
];

export const पुलिसस्टेशन = [
     { name: "Adarsh Nagar" },
     { name: "Amer" },
     { name: "Ashok Nagar" },
     { name: "Bajaj Nagar" },
     { name: "Bani Park" },
     { name: "Bapu Nagar" },
     { name: "Barkat Nagar" },
     { name: "Bassi" },
     { name: "Bhatta Basti" },
     { name: "Brahmapuri" },
     { name: "Chandpol" },
     { name: "Chitrakoot" },
     { name: "Civil Lines" },
     { name: "Durgapura" },
     { name: "Gandhi Nagar" },
     { name: "Galta Gate" },
     { name: "Ghat Gate" },
     { name: "Jhotwara" },
     { name: "Kalwar Road" },
     { name: "Kanota" },
     { name: "Karni Vihar" },
     { name: "Kotputli" },
     { name: "Lal Kothi" },
     { name: "Mansarovar" },
     { name: "Moti Doongri" },
     { name: "Nahargarh" },
     { name: "Nehru Nagar" },
     { name: "Panchyawala" },
     { name: "Pratap Nagar" },
     { name: "Rajasthan University" },
     { name: "Ramganj" },
     { name: "Sanganer" },
     { name: "Sanganer Sadar" },
     { name: "Sodala" },
     { name: "Shastri Nagar" },
     { name: "Shyam Nagar" },
     { name: "Sindhi Camp" },
     { name: "Vaishali Nagar" },
     { name: "Vidhyadhar Nagar" },
];
