export const state = [
     { name: "Andhra Pradesh", code: "AP" },
     { name: "Arunachal Pradesh", code: "AR" },
     { name: "Assam", code: "AS" },
     { name: "Bihar", code: "BR" },
     { name: "Chhattisgarh", code: "CG" },
     { name: "Goa", code: "GA" },
     { name: "Gujarat", code: "GJ" },
     { name: "Haryana", code: "HR" },
     { name: "Himachal Pradesh", code: "HP" },
     { name: "Jharkhand", code: "JH" },
     { name: "Karnataka", code: "KA" },
     { name: "Kerala", code: "KL" },
     { name: "Madhya Pradesh", code: "MP" },
     { name: "Maharashtra", code: "MH" },
     { name: "Manipur", code: "MN" },
     { name: "Meghalaya", code: "ML" },
     { name: "Mizoram", code: "MZ" },
     { name: "Nagaland", code: "NL" },
     { name: "Odisha", code: "OD" },
     { name: "Punjab", code: "PB" },
     { name: "Rajasthan", code: "RJ" },
     { name: "Sikkim", code: "SK" },
     { name: "Tamil Nadu", code: "TN" },
     { name: "Telangana", code: "TG" },
     { name: "Tripura", code: "TR" },
     { name: "Uttar Pradesh", code: "UP" },
     { name: "Uttarakhand", code: "UT" },
     { name: "West Bengal", code: "WB" },
     { name: "Andaman and Nicobar Islands", code: "AN" },
     { name: "Chandigarh", code: "CH" },
     { name: "Dadra and Nagar Haveli and Daman and Diu", code: "DD" },
     { name: "Lakshadweep", code: "LD" },
     { name: "Delhi", code: "DL" },
     { name: "Puducherry", code: "PY" },
];

export const district = [
     { name: "Ajmer", code: "AJ" },
     { name: "Alwar", code: "AL" },
     { name: "Banswara", code: "BS" },
     { name: "Baran", code: "BA" },
     { name: "Barmer", code: "BM" },
     { name: "Bharatpur", code: "BH" },
     { name: "Bhilwara", code: "BL" },
     { name: "Bikaner", code: "BK" },
     { name: "Bundi", code: "BN" },
     { name: "Chittorgarh", code: "CT" },
     { name: "Churu", code: "CR" },
     { name: "Dausa", code: "DS" },
     { name: "Dholpur", code: "DP" },
     { name: "Dungarpur", code: "DG" },
     { name: "Hanumangarh", code: "HN" },
     { name: "Jaipur", code: "JP" },
     { name: "Jaisalmer", code: "JS" },
     { name: "Jalore", code: "JR" },
     { name: "Jhalawar", code: "JW" },
     { name: "Jhunjhunu", code: "JH" },
     { name: "Jodhpur", code: "JD" },
     { name: "Karauli", code: "KR" },
     { name: "Kota", code: "KT" },
     { name: "Nagaur", code: "NG" },
     { name: "Pali", code: "PL" },
     { name: "Pratapgarh", code: "PG" },
     { name: "Rajsamand", code: "RM" },
     { name: "Sawai Madhopur", code: "SM" },
     { name: "Sikar", code: "SK" },
     { name: "Sirohi", code: "SR" },
     { name: "Sri Ganganagar", code: "SG" },
     { name: "Tonk", code: "TK" },
     { name: "Udaipur", code: "UD" },
];

export const city = [
     { name: "Jaipur", code: "JP" },
     { name: "Jodhpur", code: "JD" },
     { name: "Udaipur", code: "UD" },
     { name: "Ajmer", code: "AJ" },
     { name: "Bikaner", code: "BK" },
     { name: "Kota", code: "KT" },
     { name: "Bharatpur", code: "BH" },
     { name: "Alwar", code: "AL" },
     { name: "Sikar", code: "SK" },
     { name: "Pali", code: "PL" },
     { name: "Nagaur", code: "NG" },
     { name: "Tonk", code: "TK" },
     { name: "Sri Ganganagar", code: "SG" },
     { name: "Bhilwara", code: "BL" },
     { name: "Jhunjhunu", code: "JH" },
     { name: "Hanumangarh", code: "HN" },
     { name: "Dausa", code: "DS" },
     { name: "Barmer", code: "BM" },
     { name: "Churu", code: "CR" },
     { name: "Jaisalmer", code: "JS" },
];

export const ps = [
     { name: "Malviya Nagar", code: "MN" },
     { name: "Vaishali Nagar", code: "VN" },
     { name: "Mansarovar", code: "MS" },
     { name: "C-Scheme", code: "CS" },
     { name: "Raja Park", code: "RP" },
     { name: "Adarsh Nagar", code: "AN" },
     { name: "Jagatpura", code: "JP" },
     { name: "Bapu Nagar", code: "BN" },
     { name: "Amer", code: "AM" },
     { name: "Shastri Nagar", code: "SN" },
     { name: "Sodala", code: "SD" },
     { name: "Jhotwara", code: "JW" },
     { name: "Bani Park", code: "BP" },
     { name: "Gandhi Nagar", code: "GN" },
     { name: "Bajaj Nagar", code: "BJ" },
     { name: "Moti Doongri", code: "MD" },
     { name: "Lal Kothi", code: "LK" },
     { name: "Shyam Nagar", code: "SHN" },
     { name: "Subhash Chowk", code: "SC" },
     { name: "Transport Nagar", code: "TN" },
];

export const inputFild1 = [
     {
          name: "fname",
          type: "text",
          title: "First Name",
          placeholder: "Enter Your FirstName",
          required: true,
     },
     {
          name: "mname",
          type: "text",
          title: "Middel Name",
          placeholder: "Enter Your MiddelName",
     },
     {
          name: "lname",
          type: "text",
          title: "Last Name",
          placeholder: "Enter Your LastName",
     },
     {
          name: "password",
          type: "password",
          title: "Password",
          placeholder: "Enter Your password",
          required: true,

     },
     {
          name: "email",
          type: "email",
          title: "Email",
          placeholder: "Enter Your email",
          required: true,

     },
     {
          name: "state",
          type: "dropdown",
          title: "State",
          placeholder: "---select---",
          required: true,

     },
     {
          name: "district",
          type: "dropdown",
          title: "District",
          placeholder: "---select---",
          required: true,

     },
     {
          name: "city",
          type: "dropdown",
          title: "City",
          placeholder: "---select---",
          required: true,

     },
     {
          name: "ps",
          type: "dropdown",
          title: "Police Station",
          placeholder: "---select---",
          required: true,

     },
];
export const inputFild2 = [
     {
          name: "gender",
          type: "radio",
          title: "Gender",
          required: true,
          options: [
               { label: "Male", value: "male" },
               { label: "Female", value: "female" },
               { label: "Other", value: "other" },


          ],
     },
     {
          name: "education",
          type: "check",
          title: "Education",
          required: true,
          category: [
               { key: "B", value: "B.Teach" },
               { key: "M", value: "M.Teach" },
               { key: "O", value: "Other" },


          ],
     },
     {
          name: "sdate",
          type: "date",
          title: "Starting Date",
          placeholder: "Enter your Starting Date",
          required: true,
     },
     {
          name: "mdate",
          type: "date",
          title: "Middel Date",
          placeholder: "Enter your Middel Date",
          required: true,
     },
     {
          name: "ldate",
          type: "date",
          title: "Last Date",
          placeholder: "Enter your Last Date",
          required: true,
     },
     {
          name: "address",
          type: "textarea",
          title: "Address",
          placeholder: "Enter your address",
          required: true,
     },
     {
          name: "massege",
          type: "textarea",
          title: "Massege",
          placeholder: "Enter your Massege",
          required: true,
     },
];

export const initiValue = {
     fname: "",
     mname: "",
     lname: "",
     password: "",
     email: "",
     state: "",
     district: "",
     city: "",
     gender: "",
     education: [],
     ps: "",
     sdate: "",
     mdate: "",
     ldate: "",
     address: "",
     massege: "",
};
